[font]
name = "Petty 5H"
weight_name = "Regular"
serif_style = "Sans Serif"
slant_style = "Normal"
width_mode = "Proportional"

size = 5
ascent = 7
descent = -2
x_height = 5
cap_height = 5

fallback_lower_from_upper = true

preview_text = """
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
!"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~
"""
