[font]
name = "Petty 5H"
weight_name = "Regular"
serif_style = "Sans Serif"
slant_style = "Normal"
width_mode = "Proportional"
description = "Draw uppercase letters with minimum size by 5px height. Correspondingly, there are only uppercase letters and basic punctuation."

size = 5
ascent = 7
descent = -2
x_height = 5
cap_height = 5

fallback_lower_from_upper = true

readme_intro = "以最小尺寸 5 像素高来绘制大写字母。相应的，只有大写字母和基础标点符号。"
preview_text = """
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
!"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~
"""
