[font]
name = "Thick"
style_name = "Bold"
serif_mode = "Sans-Serif"
width_mode = "Proportional"
description = "A little thick feeling pixel font."

size = 16
ascent = 15
descent = -5
x_height = 7
cap_height = 10

readme_intro = "有一点厚重感觉的像素字体。"
