[font]
name = "Arcade"
style_name = "Regular"
serif_mode = "Sans-Serif"
width_mode = "Monospaced"
description = "Arcade Cabinet style pixel font. Design from Atari and Famicom game font."

size = 8
ascent = 9
descent = -3
x_height = 5
cap_height = 7

readme_intro = "街机风格的像素字体。设计来源于雅达利和红白机的游戏字体。"
preview_text = """
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
0123456789 ０１２３４５６７８９
!"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~
©‘’“”★♠♣♥♦
"""
