[font]
name = "Arcade"
weight_name = "Regular"
serif_style = "Sans Serif"
slant_style = "Normal"
width_mode = "Monospaced"

size = 8
ascent = 9
descent = -3
x_height = 5
cap_height = 7

preview_text = """
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
0123456789 ０１２３４５６７８９
!"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~
©‘’“”★♠♣♥♦
"""
