[font]
display_name = "Cute Mono"
unique_name = "Cute-Mono"
style_name = "Regular"
description = "The design is based on the lowercase letters with 5px height, monospaced mode."
designer = "TakWolf"
designer_url = "https://takwolf.com"
copyright_year = 2023

px = 11
line_height_px = 15
box_origin_y_px = 9
x_height_px = 5
cap_height_px = 7

readme_intro = "以小写字母为 5 像素高作为基础尺寸来设计，等宽模式。"
