[font]
name = "Cute Mono"
style_name = "Regular"
serif_mode = "Sans-Serif"
width_mode = "Monospaced"
description = "The design is based on the lowercase letters with 5px height, monospaced mode."

size = 11
line_height = 15
box_origin_y = 9
x_height = 5
cap_height = 7

readme_intro = "以小写字母为 5 像素高作为基础尺寸来设计，等宽模式。"
